try {
    console.log(great);
    
} catch (error) {
    console.log(error.name)
    console.log(error.message)
}